name: Docker Image CI for Alethic ISM Usage Monitor

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:

  build-push-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      id: code_checkout
      uses: actions/checkout@v3

    - name: Assign Environment Variables for Build & Deployment Process
      id: setup_variables
      run: |
        COMMIT_ID=$(echo $GITHUB_SHA | head -c7)
        NAMESPACE="krasaee"
        PROJECT_NAME="alethic-ism-usage"
        IMAGE="$NAMESPACE/$PROJECT_NAME:$COMMIT_ID"
        
        echo "COMMIT_ID=$COMMIT_ID" >> "$GITHUB_ENV" # for local variables
        echo "IMAGE=$IMAGE" >> "$GITHUB_ENV" # for local variables

    - name: Build Container Image
      id: build_docker_image
      run: |
        echo "COMMIT ID: $COMMIT_ID"
        echo "DOCKER IMAGE: $IMAGE"
        
        # build the docker image
        bash docker_build.sh -i $IMAGE
  
        # pass the image to the next step
        echo "IMAGE=$IMAGE" >> "$GITHUB_ENV" # for local variables

    - name: Login to Docker Hub
      id: dockerhub_login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push container image to Docker Hub Container Registry
      id: push_docker_image
      run: |
        echo "Pushing container file with image $IMAGE"
        bash docker_push.sh -i $IMAGE

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 qwake-k8s-cluster

    - name: Deploy to DigitalOcean Kubernetes
      run: |
        bash docker_deploy.sh -i $IMAGE

    - name: Verify deployment
      run: kubectl rollout status deployment/alethic-ism-usage-deployment -n alethic
