name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build and Push Docker Image
        uses: quantumwake/alethic-ism-github-actions@main
        with:
          # Required inputs
          image-name: 'krasaee/alethic-ism-usage'
          registry-username: ${{ vars.DOCKERHUB_USERNAME }}
          registry-token: ${{ secrets.DOCKERHUB_TOKEN }}
          registry: 'docker.io'
